/**
 * @file scanner.h
 * @author Gabriel Reale - Unifesp (gabrie.reale@unifesp.br)
 * @brief DFA based scanner.
 * This file defines the prototypes for the scanner abstraction.
 * The scanner must be able to tokenize a program  stored in a @ref buffer via the @ref getToken call.
 * Currently the scanner uses a dfa table for categorizing the lexemes where the ambiguity between keywords and 
 * identifiers is resolved using a variables. When a invalid token is produced a error is printed and the scanner will skip
 * the token until a valid output is found (Only valid tokens are returned to the parser).
 * The DFA's table is generated by the files inside the `dgenerate` folder, when `dgenerate/dgen.py` is called
 * the table is exported to `dgenerate/dfa.h`
 * @version 0.1
 * @date 2025-01-04
 */

#ifndef SCANNER_H
#define SCANNER_H

#include "dgenerate/states_dfa.h"
#include "buffer.h"

/**
 * @brief Struct that keeps the state of a scanner
 */
typedef struct{
    /**
     * @brief Buffer with the program being tokenized
     */
    buffer * program;
    /**
     * @brief Set to 1 when done tokenizing
     */
    int done;
    /**
     * @brief If success = 1 at the end of input the program
     * was lexically correct
     */
    int success;
    /**
     * @brief If 0 will print relevant information as the input is tokenized
     */
    int quiet;
    /**
     * @brief Current lexeme
     */
    char * lexeme;
    /**
     * @brief Current token
     */
    dfa_states token;
}scanner;

/**
 * @brief Starts a scanner struct
 * @param path path pointing to the program
 * @param quiet if 0 print scanner progres
 * @return scanner* initialized scanner
 */
scanner * createScanner(char * path, int quiet);
/**
 * @brief Destroys a scanner
 * @param s scanner to destroy<br>
 * Will free( @ref s ) <br>
 * Will call @ref destroyBuffer
 */
void destroyScanner(scanner * s);
/**
 * @brief Get the next token of the program.
 * @param s program scanner
 * @param lexeme lexeme string
 * @return dfa_states returned token
 */
dfa_states getToken(scanner * s);
#endif